import { createStyles, makeStyles } from "@material-ui/core";

export const landingStyles = makeStyles(() =>
  createStyles({
    mainContainer: {
      width: "100%",
      height: "100%",
    },
    login: {
      position: "fixed",
      color: "#FFFFFF",
      zIndex: 999,
      right: "38px",
      top: "24px",
      height: "45px",
      width: "115px",
      lineHeight: "42px",
      border: "2px solid #FFFFFF",
      textAlign: "center",
      transition: "all 0.5s ease-in-out",
      cursor: "pointer",
      "&:hover": {
        backgroundColor: "#FFFFFF",
        color: "black",
      },
    },
    header: {},
    headerLogo: {
      display: "flex",
      alignItems: "center",
      position: "absolute",
      margin: "0px",
      padding: "0px",
      left: "40px",
      top: "30px",
      zIndex: 999,
      color: "#FFFFFF",
      fontSize: "26px",
      fontWeight: "bold",
      "&>svg": {
        width: "24px",
        height: "24px",
        marginRight: "4px",
      },
      "&>span": {
        lineHeight: "24px",
      },
    },
    bodyContainer: {
      width: "100%",
      height: "100%",
      minHeight: "786px",
      backgroundColor: "transparent",
      backgroundImage: `url('/images/security.jpeg')`,
      backgroundSize: "cover",
      backgroundPosition: "center",
      backgroundRepeat: "no-repeat",
    },
    overlay: {
      position: "absolute",
      top: "0",
      left: "0",
      width: "100%",
      height: "100%",
      opacity: "0.6",
      backgroundColor: "#000000",
    },
    overlayShadow: {
      position: "absolute",
      top: "0",
      left: "0",
      width: "100%",
      height: "100%",
      opacity: "0.4",
      background:
        "linear-gradient(to bottom, transparent 0%, rgba(0, 0, 0, 0.8) 100%)",
    },
    content: {
      width: "100%",
      height: "100%",
      verticalAlign: "middle",
      paddingBottom: "150px",
      position: "relative",
      overflow: "hidden",
    },
    sideMenu: {},
    main: {
      animationDuration: "2s",
      animationName: "fadeIn",
      paddingTop: "300px",
      position: "relative",
      margin: "0 auto",
      width: "94%",
      maxWidth: "1000px",
    },
    buttonLayout: {
      paddingTop: "60px",
      textAlign: "left",
    },
    homeButton: {
      width: "215px",
      border: "2px solid #FFFFFF",
      color: "#FFFFFF",
      margin: "15px 15px 0px 0px",
      transition: "all 0.5s ease-in-out",
      textTransform: "uppercase",
      textAlign: "center",
      fontSize: "14px",
      fontWeight: "bold",
      height: "50px",
      lineHeight: "45px",
      display: "inline-block",
      textDecoration: "none",
      "&:hover": {
        backgroundColor: "#FFFFFF",
        color: "black",
      },
    },
    title: {
      color: "rgba(255, 255, 255, 0.5)",
      textTransform: "uppercase",
      letterSpacing: ".3rem",
      marginTop: "0px",
      marginBottom: "1.2rem",
      marginLeft: "6px",
      lineHeight: "1.25",
    },
    description: {
      fontSize: "60px",
      lineHeight: "1.333",
      marginTop: "0px",
      color: "#FFFFFF",
      letterSpacing: "-.1rem",
      marginBottom: "1.8rem",
    },
  })
);
