import { createStyles, makeStyles } from "@material-ui/core";

export const loginStyles = makeStyles(() =>
  createStyles({
    mainContainer: { width: "100%", margin: "0px auto", fontWeight: "bold" },
    loginBox: {
      width: "100%",
      minHeight: "100vh",
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
      alignItems: "center",
      padding: "15px",
      position: "relative",
      backgroundColor: "#e6e6e6",
    },
    wrapper: {
      width: "320px",
      background: "transparent",
      borderRadius: "0px",
      paddingTop: "90px",
      marginBottom: "30px",
    },
    header: {
      fontSize: "30px",
      color: "#43383e",
      lineHeight: "1.2",
      textAlign: "center",
      paddingBottom: "40px",
    },
    connection: {},
    facebook: {
      transition: "all 0.4s",
      margin: "0px",
      fontSize: "16px",
      color: "#ffffff",
      lineHeight: "1.2",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
      height: "50px",
      borderRadius: "25px",
      backgroundColor: "#3b5998",
      marginBottom: "10px",
      textDecoration: "none",
      "&:focus": {
        outline: "none !important",
      },
      "&:hover": {
        color: "#ffffff",
        backgroundColor: "#333333",
      },
      "&>svg": {
        marginRight: "6px",
        width: "20px",
        height: "20px",
      },
    },
    google: {
      transition: "all 0.4s",
      margin: "0px",
      fontSize: "16px",
      color: "#ffffff",
      lineHeight: "1.2",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
      height: "50px",
      borderRadius: "25px",
      backgroundColor: "#1da1f2",
      marginBottom: "10px",
      textDecoration: "none",
      "&:focus": {
        outline: "none !important",
      },
      "&:hover": {
        color: "#ffffff",
        backgroundColor: "#333333",
      },
      "&>svg": {
        marginRight: "6px",
        width: "20px",
        height: "20px",
      },
    },
    subHeader: {
      textAlign: "center",
      paddingTop: "55px",
      paddingBottom: "30px",
      fontSize: "20px",
      color: "#333333",
      lineHeight: "1.2",
    },
    id: {
      width: "100%",
      backgroundColor: "#ffffff",
      borderRadius: "31px",
      position: "relative",
      zIndex: 1,
      marginBottom: "16px",
    },
    password: {
      width: "100%",
      backgroundColor: "#ffffff",
      borderRadius: "31px",
      position: "relative",
      zIndex: 1,
      marginBottom: "20px",
    },
    input: {
      fontSize: "16px",
      color: "#433383e",
      lineHeight: "1.2",
      position: "relative",
      display: "block",
      width: "100%",
      height: "62px",
      background: "#ffffff",
      borderRadius: "31px",
      padding: "0px 35px",
    },
    focusInput: {
      display: "block",
      position: "absolute",
      zIndex: -1,
      width: "100%",
      height: "100%",
      top: "0",
      left: "50%",
      transform: "translateX(-50%)",
      borderRadius: "31px",
      backgroundColor: "#ffffff",
      pointerEvents: "none",
      transition: "all 0.4s",
    },
    showPasswd: {
      fontSize: "15px",
      display: "flex",
      alignItems: "center",
      color: "#aaaaaa",
      position: "absolute",
      zIndex: 200,
      height: "100%",
      top: "0",
      right: "25px",
      padding: "0 5px",
      cursor: "pointer",
      transition: "background 0.4s",
      "&:hover": {
        color: "#111111",
      },
      "&:active": {
        color: "#111111",
      },
      "&>svg": {
        width: "18px",
        height: "18px",
      },
    },
    login: {
      width: "100%",
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
    },
    loginButton: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      padding: "0 20px",
      minWidth: "160px",
      height: "62px",
      backgroundColor: "transparent",
      borderRadius: "31px",
      fontSize: "16px",
      color: "#ffffff",
      lineHeight: "1.2",
      transition: "all 0.4s",
      position: "relative",
      zIndex: 1,
      "&::before": {
        content: "''",
        display: "block",
        position: "absolute",
        zIndex: -1,
        width: "100%",
        height: "100%",
        top: "0",
        left: "50%",
        transform: "translateX(-50%)",
        borderRadius: "31px",
        backgroundColor: "#333333",
        pointerEvents: "none",
        transition: "all 0.4s",
      },
      "&:hover:before": {
        backgroundColor: "#222222",
        width: "calc(100% + 20px)",
      },
    },
    signup: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      paddingTop: "224px",
    },
    signupContent: {
      fontSize: "16px",
      color: "#999999",
      lineHeight: "1.4",
    },
    signupButton: {
      fontSize: "16px",
      color: "#333333",
      lineHeight: "1.2",
      borderBottom: "1px solid #929292",
      textDecoration: "none",
      "&:hover": {
        borderBottom: "1px solid #111111",
        color: "#111111",
        fontSize: "17px",
      },
    },
    headerLogo: {
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      position: "absolute",
      margin: "0px",
      padding: "0px",
      left: "40px",
      top: "30px",
      zIndex: 999,
      color: "black",
      fontSize: "26px",
      fontWeight: "bold",
      backgroundColor: "#E6E6E6",
      "&>svg": {
        width: "24px",
        height: "24px",
        marginRight: "4px",
        color: "black",
      },
      "&>span": {
        lineHeight: "24px",
      },
    },
  })
);
